algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
procedimento mult(n1,n2: inteiro)
var
  res: inteiro
inicio
  res <- n1 * n2
  escreva("A multiplicação do números é: ", res)

fimprocedimento

var


inicio
  escreva(mult(5, 10))

fimalgoritmo